steps:
   - id: "Setup gcloud"
    name: "gcr.io/cloud-builders/gcloud"
    entrypoint: 'bash'
    args:
    - '-c' # pass what follows as a command to bash
    - |
      gcloud config set project ${PROJECT_ID}

  - id: "Build docker image"
    name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "asia-docker.pkg.dev/${PROJECT_ID}/${_SERVICE_NAME}/${_SERVICE_NAME}",
        ".",
      ]

  - id: "Update cloud run service"
    name: "gcr.io/${PROJECT_ID}/terraform"
    entrypoint: 'bash'
    args:
    - '-c' # pass what follows as a command to bash
    - |
      terraform -chdir=terraform init
      terraform -chdir=terraform import google_cloud_run_service.cloud-resume-challenge asia-east1/${PROJECT_ID}/${_SERVICE_NAME}
      terraform -chdir=terraform destroy -auto-approve
      terraform -chdir=terraform apply -auto-approve -var project=${PROJECT_ID}

options:
  logStreamingOption: STREAM_ON

substitutions:
  _SERVICE_NAME: cloud-resume-challenge

images:
  - "asia-docker.pkg.dev/${PROJECT_ID}/${_SERVICE_NAME}/${_SERVICE_NAME}"