steps:
  - id: "Build docker image"
    name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "asia-docker.pkg.dev/${PROJECT_ID}/${_SERVICE_NAME}/${_SERVICE_NAME}",
        ".",
      ]

  - id: "Update cloud run service"
    name: "gcr.io/${PROJECT_ID}/terraform"
    entrypoint: 'bash'
    args:
    - '-c' # pass what follows as a command to bash
    - |
      terraform -chdir=terraform init
      terraform -chdir=terraform import google_cloud_run_service.cloud-resume-challenge ${PROJECT_ID}
      terraform -chdir=terraform destroy
      terraform -chdir=terraform apply


options:
  logStreamingOption: STREAM_ON

substitutions:
  _SERVICE_NAME: cloud-resume-challenge

images:
  - "asia-docker.pkg.dev/${PROJECT_ID}/${_SERVICE_NAME}/${_SERVICE_NAME}"